pipeline {
    agent any
    
    environment {
        // Customize these variables
        DOCKER_IMAGE = 'test'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        GITHUB_REPO_URL = 'https://github.com/RazSherf/Stocker'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub repository
                git branch: 'jenkins', 
                    url: "${GITHUB_REPO_URL}"
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "-f backend/Dockerfile backend")
                }
            }
        }
        
        stage('Run Docker Image') {
            steps {
                script {
                    // Run the Docker image in a container
                    sh """
                        docker run -d --name test-container -p 8081:8080 ${DOCKER_IMAGE}:${DOCKER_TAG}
                        echo "Container is running on port 8081"
                    """
                }
            }
        }
    }
    
    post {
        success {
            echo 'Pipeline completed successfully! Docker image built, and container is running.'
        }
        failure {
            echo 'Pipeline failed. Check the logs for details.'
        }
        
    }
}